### ISSUE TITLE
createTx problem

### ISSUE THREAD

**Issue by michaeljoser** [epexa/metahash-js#1]
Hello! thank you for this code... works very nicely.  Only problem i am having is when creating a transaction,  i am getting this error below:

createTx { code: -32602,
  message:
   'Incorrect func mhc_send. Error at file /home/user/torrent-node/src/Server.cpp line 454. Url: /' }

any tips on your side?

**Comment by epexa** [comment]
@michaeljoser Hi! Thank you!

I think in your specified node address does not support create transaction. You need to specify a another node address.

**Comment by michaeljoser** [comment]
thank you for the quick reply.  i have tried so many servers from this
```
$ host proxy.net-main.metahashnetwork.com
proxy.net-main.metahashnetwork.com has address 206.189.13.140
proxy.net-main.metahashnetwork.com has address 172.104.239.101
proxy.net-main.metahashnetwork.com has address 206.189.13.155
proxy.net-main.metahashnetwork.com has address 139.162.157.232
proxy.net-main.metahashnetwork.com has address 96.126.100.131
```
most of them i get this error:
```
 FetchError: request to http://139.162.157.232:5795/ failed, reason: connect ECONNREFUSED 139.162.157.232:5795
```

quick update.. i was using wrong port 5795 on the proxy servers.. should be using port 9999 . silly me

**Comment by epexa** [comment]
i think problem is in bad documentation.
